---
application:
  port: 3000
  host: 127.0.0.1
  logfile_path: ./maedic.log
  service_name: micserver.exe
database:
  host: 127.0.0.1
  port: 1433
  username: sa
  password: Charlie 13
  database_name: PWNT
  trust_cert: true
limits:
  hi_queue_count: 1000
  spool_file_count: 10 #max no of spool files acceptable for a healthy channel
  max_ram_percentage: 80.0
  max_cpu_percentage: 80.0
