-- /****** Object:  UserDefinedTableType [dbo].[AuditLogEntry]    Script Date: 16.04.2026 11:29:24 ******/
-- CREATE TYPE [dbo].[AuditLogEntry] AS TABLE(
--     [BatchId] [varbinary](18) NOT NULL,
--     [TableName] [varchar](50) NOT NULL,
--     [ColumnName] [varchar](50) NOT NULL
-- )
-- GO
-- /****** Object:  UserDefinedTableType [dbo].[BadgingFieldsTable]    Script Date: 16.04.2026 11:29:24 ******/
-- CREATE TYPE [dbo].[BadgingFieldsTable] AS TABLE(
--     [ColumnName] [varchar](128) NOT NULL
-- )
-- GO
-- /****** Object:  UserDefinedTableType [dbo].[BadgingFilterTable]    Script Date: 16.04.2026 11:29:24 ******/
-- CREATE TYPE [dbo].[BadgingFilterTable] AS TABLE(
--     [ColumnName] [varchar](128) NOT NULL,
--     [ColumnValue] [varchar](128) NOT NULL
-- )
-- GO
-- /****** Object:  UserDefinedTableType [dbo].[PWVP_DEACTIVATE_CARD_TYPE]    Script Date: 16.04.2026 11:29:24 ******/
-- CREATE TYPE [dbo].[PWVP_DEACTIVATE_CARD_TYPE] AS TABLE(
--     [FieldName] [nvarchar](100) NULL,
--     [FieldValue] [nvarchar](max) NULL,
--     [FieldDisplay] [nvarchar](max) NULL
-- )
-- GO
